### ISSUE TITLE
Multi Mission planning is broken

### ISSUE THREAD

**Issue by b14ckyy** [stronnag/mwptools#129]
If I plan a waypoint mission and then add a second one, the first mission stays on screen. 
Any further added waypoint is then just continuing the existing ones.

When I switch back to Mission 1, only the first mission is shown. Switching to 2 then shows all waypoints of both planned missions. 
After loading the missions to the FC they are also stored exactly that way. Mission 1 has 5 waypoints for example but Mission 2 then has 10 waypoints. 

I can delete the waypoints 1-5 in mission 2 initially but when I try to switch back to Mission 1, the application crashes. 

Seen on Versions: 5.295.580 4d6e772 and current master 5.311.575 c3008c0
OS: WSL2 Windows 11
FC Firmware independent

![image](https://user-images.githubusercontent.com/33039058/207600613-6f0930c3-115c-4bcb-9f33-780f2fc774fe.png)
![image](https://user-images.githubusercontent.com/33039058/207600691-4dddc100-d9f9-459e-a9db-9063b188eb65.png)

INAV Configurator shows them as expected. Either ALL or Single mission: 
![image](https://user-images.githubusercontent.com/33039058/207600439-c0f66f63-75e1-4dee-8ff7-99e94c0f955d.png)
![image](https://user-images.githubusercontent.com/33039058/207600484-9e3329d2-97a4-4e8f-af07-18cb74e9a2ce.png)

**Comment by stronnag** [comment]
Confirmed . Thanks

**Comment by b14ckyy** [comment]
btw just one minor thing. 
When "Edit Waypoints" is active and I pan through the map, every time I release the left mouse button it creates a waypoint. 
its just a minor inconvenience but while you're at it, maybe this can be fixed as well?

**Comment by stronnag** [comment]
Should be fixed in master (and development) branches. I'll maybe build a `.deb` later.

**Comment by b14ckyy** [comment]
Great! Multi Mission switching works now properly and the WP creation during mouse panning is also fixed. 
One issue remains though: The crash when deleting multiple waypoints at the beginning of the mission. Does not seem to be related to multi mission. 

Creating 10 waypoints in a row. Then select WP 1-5 in the WP list. Right click and delete selection. Application crashes. 
It just says "Segmentation Fault" in the shell. Nothing in the mwp_stderr_2022-12-14.txt

**Comment by stronnag** [comment]
I can't reproduce this crash on current master (but I did see it on an older build).

**Comment by stronnag** [comment]
There is no more useful logging for this case. I'll try on a Win11 VM when I can evict Mrs Stonnag from the desktop computer.

**Comment by b14ckyy** [comment]
No Rush. Right now I can work around that. Just needed multi mission with Useraction support for a test and INAV Mission Control does not support Useractions yet. So thanks a lot for your quick response.

**Comment by stronnag** [comment]
Same crash here on win11/WSL-G. Next up native Debian / Ubuntu / FreeBSD.

**Comment by stronnag** [comment]
> I place a bet on Ubuntu as well.

Hope so, then there is a possibility to see why

**Comment by stronnag** [comment]
Reworked the way bulk delete works. Please try the latest master (or development). I could get it to crash on Ub 22.04 after multiple bulk-deletes. So it's now simpler ...

**Comment by b14ckyy** [comment]
Perfect! All working now. crated 50 waypoints and deleted the first 20 with no issue. 
Thanks a lot mate!
